authors = ["<oss@fastly.com>"]
description = ""
language = "rust"
manifest_version = 3
name = "Perform multiple origin requests asynchronously"

[local_server.backends.origin_0]
      url = "https://httpbin.org"

[local_server.backends.origin_1]
      url = "https://httpbin.org"

[setup.backends.origin_0]
address = "httpbin.org"
port = 443

[setup.backends.origin_1]
address = "httpbin.org"
port = 443
